-- ============================================================================
-- Migration: Initial Schema for 10x-cards
-- Description: Creates all core tables for flashcard management system
-- Tables: profiles, decks, cards, reviews, ai_generation_logs
-- Features: RLS policies, indexes, triggers for updated_at
-- ============================================================================
-- Note: Users table is managed by Supabase Auth (auth.users)
-- This migration creates a profiles table to extend user data
-- ============================================================================

-- ============================================================================
-- EXTENSIONS
-- ============================================================================

-- Enable UUID generation (if not already enabled)
create extension if not exists "uuid-ossp";

-- ============================================================================
-- TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Table: profiles
-- Purpose: Extends auth.users with application-specific user data
-- RLS: Enabled - users can only access their own profile
-- ----------------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  privacy_consent boolean not null default false,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  
  -- Soft delete constraint: ensure deleted_at is in the past or null
  constraint valid_deleted_at check (deleted_at is null or deleted_at <= now())
);

comment on table public.profiles is 'User profile data extending Supabase Auth users';
comment on column public.profiles.id is 'References auth.users(id) - one-to-one relationship';
comment on column public.profiles.privacy_consent is 'User consent for AI processing of their data';
comment on column public.profiles.deleted_at is 'Soft delete timestamp - NULL means active account';

-- ----------------------------------------------------------------------------
-- Table: decks
-- Purpose: Stores flashcard deck information
-- RLS: Enabled - users can only access their own decks
-- ----------------------------------------------------------------------------
create table public.decks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name varchar(255) not null,
  created_by_ai boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  
  -- Business rule: deck name cannot be empty
  constraint non_empty_name check (trim(name) <> '')
);

comment on table public.decks is 'Flashcard decks owned by users';
comment on column public.decks.user_id is 'Owner of the deck';
comment on column public.decks.created_by_ai is 'Flag indicating if deck was generated by AI';

-- ----------------------------------------------------------------------------
-- Table: cards
-- Purpose: Individual flashcards with SM-2 spaced repetition algorithm data
-- RLS: Enabled - users can access cards from their own decks
-- ----------------------------------------------------------------------------
create table public.cards (
  id uuid primary key default gen_random_uuid(),
  deck_id uuid not null references public.decks(id) on delete cascade,
  question text not null,
  answer text not null,
  ease_factor decimal(3,2) not null default 2.50,
  interval_days integer not null default 1,
  repetitions integer not null default 0,
  next_review_date timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  
  -- SM-2 algorithm constraints
  constraint valid_ease_factor check (ease_factor between 1.30 and 2.50),
  constraint valid_interval_days check (interval_days >= 1),
  constraint valid_repetitions check (repetitions >= 0),
  
  -- Business rules: question and answer cannot be empty
  constraint non_empty_question check (trim(question) <> ''),
  constraint non_empty_answer check (trim(answer) <> ''),
  
  -- Length constraints as per schema (10000 chars)
  constraint question_length check (length(question) <= 10000),
  constraint answer_length check (length(answer) <= 10000)
);

comment on table public.cards is 'Flashcards with SM-2 spaced repetition algorithm data';
comment on column public.cards.ease_factor is 'SM-2 ease factor (1.30-2.50) - measures card difficulty';
comment on column public.cards.interval_days is 'SM-2 interval - days until next review';
comment on column public.cards.repetitions is 'SM-2 repetitions count - number of successful reviews';
comment on column public.cards.next_review_date is 'Scheduled date for next review';

-- ----------------------------------------------------------------------------
-- Table: reviews
-- Purpose: Historical record of card review sessions and grades
-- RLS: Enabled - users can only access their own reviews
-- ----------------------------------------------------------------------------
create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.cards(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  grade integer not null,
  review_date timestamptz not null default now(),
  
  -- SM-2 grade constraint (0-5)
  -- 0: complete blackout, 1: incorrect response with correct answer seemed familiar
  -- 2: incorrect response with correct answer seemed easy to recall
  -- 3: correct response recalled with serious difficulty
  -- 4: correct response after hesitation, 5: perfect response
  constraint valid_grade check (grade between 0 and 5)
);

comment on table public.reviews is 'Historical record of card reviews with SM-2 grades';
comment on column public.reviews.grade is 'SM-2 grade (0-5) where 0=total forget, 5=perfect recall';
comment on column public.reviews.review_date is 'Timestamp when review was completed';

-- ----------------------------------------------------------------------------
-- Table: ai_generation_logs
-- Purpose: Audit log for AI-generated flashcard operations
-- RLS: Enabled - users can only access their own logs
-- ----------------------------------------------------------------------------
create table public.ai_generation_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  deck_id uuid references public.decks(id) on delete set null,
  input_text_length integer not null,
  generated_cards_count integer not null default 0,
  error_message text,
  created_at timestamptz not null default now(),
  
  -- Business rules: lengths and counts must be non-negative
  constraint valid_input_length check (input_text_length >= 0),
  constraint valid_cards_count check (generated_cards_count >= 0)
);

comment on table public.ai_generation_logs is 'Audit log for AI flashcard generation operations';
comment on column public.ai_generation_logs.deck_id is 'Target deck (NULL if creating new deck)';
comment on column public.ai_generation_logs.error_message is 'Error details (NULL on success)';

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.decks enable row level security;
alter table public.cards enable row level security;
alter table public.reviews enable row level security;
alter table public.ai_generation_logs enable row level security;

-- ----------------------------------------------------------------------------
-- NOTE: RLS is enabled but no policies are defined
-- All access will be denied until policies are explicitly added
-- ----------------------------------------------------------------------------

-- ============================================================================
-- INDEXES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Indexes for profiles table
-- ----------------------------------------------------------------------------

-- Index for soft delete queries (finding active users)
create index idx_profiles_deleted_at 
  on public.profiles(deleted_at) 
  where deleted_at is null;

comment on index idx_profiles_deleted_at is 'Partial index for active users (deleted_at IS NULL)';

-- ----------------------------------------------------------------------------
-- Indexes for decks table
-- ----------------------------------------------------------------------------

-- Index for filtering decks by user (most common query pattern)
create index idx_decks_user_id 
  on public.decks(user_id);

comment on index idx_decks_user_id is 'Speed up queries filtering decks by user';

-- Index for finding AI-generated decks
create index idx_decks_created_by_ai 
  on public.decks(created_by_ai) 
  where created_by_ai = true;

comment on index idx_decks_created_by_ai is 'Partial index for AI-generated decks';

-- ----------------------------------------------------------------------------
-- Indexes for cards table
-- ----------------------------------------------------------------------------

-- Index for filtering cards by deck (most common query pattern)
create index idx_cards_deck_id 
  on public.cards(deck_id);

comment on index idx_cards_deck_id is 'Speed up queries filtering cards by deck';

-- Index for finding cards due for review
create index idx_cards_next_review_date 
  on public.cards(next_review_date);

comment on index idx_cards_next_review_date is 'Speed up queries filtering/sorting by review date';

-- Composite index for user's cards due for review (optimization for common query)
-- Note: Requires join with decks table but optimizes the full query path
create index idx_cards_deck_review 
  on public.cards(deck_id, next_review_date);

comment on index idx_cards_deck_review is 'Composite index for deck + review date queries';

-- ----------------------------------------------------------------------------
-- Indexes for reviews table
-- ----------------------------------------------------------------------------

-- Index for filtering reviews by card (for card history)
create index idx_reviews_card_id 
  on public.reviews(card_id);

comment on index idx_reviews_card_id is 'Speed up queries for card review history';

-- Index for filtering reviews by user
create index idx_reviews_user_id 
  on public.reviews(user_id);

comment on index idx_reviews_user_id is 'Speed up queries for user review history';

-- Index for chronological review queries
create index idx_reviews_review_date 
  on public.reviews(review_date desc);

comment on index idx_reviews_review_date is 'Speed up chronological review queries';

-- Composite index for user's reviews over time
create index idx_reviews_user_date 
  on public.reviews(user_id, review_date desc);

comment on index idx_reviews_user_date is 'Composite index for user review timeline';

-- ----------------------------------------------------------------------------
-- Indexes for ai_generation_logs table
-- ----------------------------------------------------------------------------

-- Index for filtering logs by user
create index idx_ai_logs_user_id 
  on public.ai_generation_logs(user_id);

comment on index idx_ai_logs_user_id is 'Speed up queries for user AI generation logs';

-- Index for filtering logs by deck
create index idx_ai_logs_deck_id 
  on public.ai_generation_logs(deck_id) 
  where deck_id is not null;

comment on index idx_ai_logs_deck_id is 'Partial index for logs associated with specific decks';

-- Index for chronological log queries
create index idx_ai_logs_created_at 
  on public.ai_generation_logs(created_at desc);

comment on index idx_ai_logs_created_at is 'Speed up chronological log queries';

-- ============================================================================
-- FUNCTIONS & TRIGGERS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Function: update_updated_at_column
-- Purpose: Automatically update updated_at timestamp on row modification
-- Usage: Attached as BEFORE UPDATE trigger on tables with updated_at column
-- ----------------------------------------------------------------------------
create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

comment on function public.update_updated_at_column is 'Trigger function to auto-update updated_at timestamp';

-- ----------------------------------------------------------------------------
-- Triggers: updated_at automation
-- ----------------------------------------------------------------------------

-- Trigger for profiles table
create trigger set_updated_at_profiles
  before update on public.profiles
  for each row
  execute function public.update_updated_at_column();

-- Trigger for decks table
create trigger set_updated_at_decks
  before update on public.decks
  for each row
  execute function public.update_updated_at_column();

-- Trigger for cards table
create trigger set_updated_at_cards
  before update on public.cards
  for each row
  execute function public.update_updated_at_column();

-- Note: reviews and ai_generation_logs tables don't have updated_at columns
-- as they are typically immutable (append-only logs)

-- ============================================================================
-- HELPER FUNCTION: Auto-create profile on user signup
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Function: handle_new_user
-- Purpose: Automatically create a profile entry when a new user signs up
-- Trigger: After INSERT on auth.users
-- ----------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, privacy_consent, created_at, updated_at)
  values (new.id, false, now(), now());
  return new;
end;
$$;

comment on function public.handle_new_user is 'Auto-create profile on user signup';

-- Create trigger on auth.users table to auto-create profiles
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================

